FROM gmpfuzz/mqtt

USER root

RUN apt-get update && \
    apt-get install -y gcc g++ cmake git make libssl-dev libcjson-dev wget clang libedit-dev libmicrohttpd-dev libsqlite3-dev

WORKDIR /opt

RUN git clone https://github.com/eclipse/mosquitto.git && \
    cd /opt/mosquitto && \
    git checkout v2.1.2 && \
    sed -i 's/^CFLAGS:=/CFLAGS:=-fsanitize=address -g /g' config.mk && \
    sed -i 's/^LDFLAGS:=/LDFLAGS:=-fsanitize=address -g /g' config.mk && \
    make WITH_WEBSOCKETS=no WITH_TLS=no WITH_DOCS=no WITH_HTTP_API=no WITH_EDITLINE=no

RUN chmod 777 -R /opt/mosquitto
